function formatValue(value: unknown): string {
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') return String(value);
  // JSON.stringify handles escaping quotes, backslashes, newlines, etc.
  return JSON.stringify(value);
}

function formatEntry(entry: Record<string, unknown>, indent: string): string {
  const lines = Object.entries(entry).map(
    ([key, value]) => `${indent}  ${key}: ${formatValue(value)},`
  );
  return `${indent}{\n${lines.join('\n')}\n${indent}}`;
}

export function formatAsTypeScript(data: Record<string, unknown>[]): string {
  const entries = data.map((entry) => formatEntry(entry, '  ')).join(',\n');

  return `// Auto-generated by npm-license-scraper
export const licenses = [
${entries},
] as const;

export type License = (typeof licenses)[number];
`;
}
